from __future__ import annotations

from typing import Dict, Iterable, List, Mapping


REQUIRED_FIELD_SECTIONS = (
    "title",
    "summary",
    "unit",
    "location",
    "effect",
    "constraints",
    "example",
    "model_status",
)

REQUIRED_CONTROL_SECTIONS = (
    "title",
    "summary",
    "inputs",
    "state",
    "cadence",
    "decision",
    "action",
    "recovery",
    "priority",
    "forward_progress",
    "evidence",
    "boundary",
)


def _field(
    title: str,
    summary: str,
    unit: str,
    location: str,
    effect: str,
    constraints: str,
    example: str,
    model_status: str = "当前模型已实现",
) -> Dict[str, str]:
    return {
        "title": title,
        "summary": summary,
        "unit": unit,
        "location": location,
        "effect": effect,
        "constraints": constraints,
        "example": example,
        "model_status": model_status,
    }


PARAMETER_METADATA: Dict[str, Dict[str, str]] = {
    "duration_ns": _field(
        "仿真时间",
        "一次任务从0开始推进到该结束时间，用于决定流量注入、稳态观察和统计窗口数量。",
        "ns",
        "离散事件内核的全局停止条件。",
        "增大后可观察更长稳态和恢复过程，但事件数量及运行时间近似线性增加。",
        "10,000到5,000,000，且控制周期不能大于仿真时间。",
        "500000表示仿真0.5 ms。",
    ),
    "control_interval_ns": _field(
        "控制与导出周期",
        "周期性采集CPU、L3、MC和控制记录，并触发当前慢速闭环策略。",
        "ns",
        "监控收集器和closed_loop_qos策略。",
        "减小可提高可见时间分辨率，但会增加快照数量；它不是L3/MC目标256本地拍监控周期。",
        "至少1,000，不能大于仿真时间，最多生成1,000个周期。",
        "50000表示每50 us输出一次周期结果。",
        "当前模型已实现；目标规格将拆分L3和MC本地时钟监控周期",
    ),
    "seed": _field(
        "随机种子",
        "控制随机地址、注入抖动和当前概率L3命中的确定性随机序列。",
        "无",
        "流量生成器和L3随机命中模型。",
        "相同配置和seed应产生相同结果；改变seed用于观察统计波动。",
        "0到2,147,483,647。",
        "1234可用于可复现实验。",
    ),
    "active_cores": _field(
        "活跃核数",
        "Web参考场景中参与建模的CPU core数量。",
        "core",
        "参考拓扑和16线程requester映射。",
        "决定requester数量及共享L3、NoC和MC的竞争来源。",
        "当前Web场景固定为8，只读；YAML/Python接口允许其他拓扑。",
        "8核与每核2线程组成16个硬件线程。",
        "Web参考场景固定值",
    ),
    "threads_per_core": _field(
        "每核线程数",
        "Web参考场景中每个core包含的硬件线程数量。",
        "thread/core",
        "requester自动展开。",
        "与活跃核数共同决定激励行和requester映射。",
        "当前Web场景固定为2，只读。",
        "cpu3.t0和cpu3.t1属于同一个core。",
        "当前模型已实现两线程共享Core OSTD池",
    ),
    "max_outstanding": _field(
        "Thread最大OSTD",
        "每个硬件线程可同时占用的事务跟踪项上限；请求最终完成后释放计数。",
        "request",
        "CPU RN事务表分配前的线程级准入。",
        "增大可提高该线程内存级并行度；实际还受Core池和目标MC的CBusy上限约束。",
        "1到1024；CBusy L1/L2/L3 OSTD上限都不能超过它。",
        "32表示每个硬件线程最多占用32个未完成事务项。",
    ),
    "core_max_outstanding": _field(
        "Core最大OSTD",
        "同一个物理core内两个SMT线程共享的事务跟踪资源总容量。",
        "request/core",
        "CPU RN事务表分配前的core共享池准入。",
        "它可小于两个Thread上限之和，用于模拟共享硬件表；达到上限后两个线程都停止新分配。",
        "1到2048；reserve_borrow模式下必须容纳所有线程保留份额。",
        "48表示两个Thread各自上限32，但同一时刻合计最多48。",
    ),
    "core_ostd_policy": _field(
        "Core OSTD分配策略",
        "选择两个SMT线程如何使用共享Core OSTD池。",
        "枚举",
        "CoreOstdPool的新事务准入与线程轮询。",
        "shared完全共享；static_partition固定切分；reserve_borrow保留每线程底线并允许使用非保留空间。",
        "只能选择shared、static_partition或reserve_borrow。",
        "reserve_borrow配合每线程保留8，可避免一个线程完全吞掉共享池。",
    ),
    "thread_ostd_reserve": _field(
        "Thread保留OSTD",
        "reserve_borrow策略下为每个SMT线程预留的最低可用事务项数量。",
        "request/thread",
        "CoreOstdPool的保留和借用判定。",
        "线程超过自己的保留份额后，只能使用未被其他线程保留的空间；其他策略下仅显示、不参与判定。",
        "1到Core最大OSTD；reserve_borrow模式下还必须不超过Thread上限，且保留总和不能超过Core容量。",
        "Core容量48、每线程保留8时，共保留16项，剩余32项可动态竞争。",
    ),
    "l3_instances": _field(
        "L3实例数",
        "参考拓扑中独立共享L3/SLC MSC的数量。",
        "instance",
        "core到L3的cluster映射。",
        "实例增多通常减少每实例竞争，但也改变每个实例独立MPAM控制和监控域。",
        "1到活跃核数，Web上限8。",
        "2表示每4个core共享一个L3。",
    ),
    "l3_sets": _field(
        "L3 Set数",
        "每个L3实例的set数量，与way数和line bytes共同决定物理容量。",
        "set/instance",
        "L3容量、地址set映射和抽样set数量。",
        "增大容量并增加sampled-owner状态规模。",
        "8到262,144；当前Web要求8的倍数。",
        "32768 sets、16 ways、64B line约为32 MiB。",
    ),
    "l3_ways": _field(
        "每Set Way数",
        "每个set可容纳的cache line数量，也是CPBM有效位宽。",
        "way/set",
        "L3容量、sampled-owner数组和CPBM way资格判断。",
        "增大可提高关联度和容量，同时扩大替换比较与CPBM状态。",
        "1到32；CPBM不能设置超过该位宽的bit。",
        "16 ways对应CPBM 0xffff。",
    ),
    "l3_line_size": _field(
        "Cache Line大小",
        "地址set/tag映射、容量计算和L3占用记账的粒度。",
        "byte",
        "L3地址映射和容量换算。",
        "增大会减少同容量下line数量，并改变地址映射和抽样占用字节。",
        "16到256，当前界面步长16；目标规格要求2的幂。",
        "64表示每条cache line为64B。",
    ),
    "l3_monitor_group_sets": _field(
        "L3抽样分组",
        "每组set只取第一个set维护way owner，并按分组大小放大访问量和占用估计。",
        "set/group",
        "L3近似MPAM监控。",
        "抽样比例越低，状态更少但监控值与全量真实占用偏差可能更大。",
        "当前固定为8，只读。",
        "set 0、8、16等被抽样，其余set不维护owner。",
        "当前模型已实现的近似监控",
    ),
    "l3_hit_latency_ns": _field(
        "L3 Lookup延迟",
        "请求开始L3查询后到返回当前概率命中或未命中结果的固定时间。",
        "ns",
        "L3 lookup槽位服务时间和cache_delay。",
        "增大会降低lookup吞吐并增加命中、未命中请求的公共延迟。",
        "1到500。",
        "20表示lookup槽位被占用20 ns。",
        "当前命中和miss检测共用一个延迟；目标规格将拆分hit、miss detection和fill延迟",
    ),
    "l3_queue_depth": _field(
        "L3请求队列深度",
        "每个L3实例在lookup槽位前可等待的FIFO entry数量。",
        "entry/instance",
        "L3入口准入和queue delay。",
        "增大可吸收突发但可能放大排队尾延迟；队列满时请求定时重试。",
        "1到8192。",
        "128表示最多128个请求等待lookup。",
    ),
    "l3_lookup_parallelism": _field(
        "L3 Lookup并发槽",
        "每个L3实例可同时进行的抽象tag/data lookup数量。",
        "slot/instance",
        "L3队列到lookup执行阶段。",
        "增大可提高lookup吞吐并降低排队，但不等同于真实bank、pipeline或MSHR数量。",
        "1到1024。",
        "16表示最多16个并发lookup。",
        "当前抽象并发模型",
    ),
    "noc_routers": _field(
        "NoC Router数",
        "当前抽象mesh拓扑中的router数量，用于requester附着和平均跳数推导。",
        "router",
        "NoC拓扑构建。",
        "改变平均跳数和固定传输延迟。",
        "1到64。",
        "8个router会生成对应core attach node。",
        "当前旧NoC模型；目标规格将替换为三条双向bufferless ring",
    ),
    "noc_link_gbps": _field(
        "NoC链路带宽",
        "当前NoC瓶颈链路用于计算请求序列化间隔的带宽。",
        "Gbps",
        "NoC队列服务。",
        "减小会增加NoC排队和源端重试。",
        "1到4096。",
        "256 Gbps时64B传输的理想序列化约2 ns。",
        "当前旧NoC模型；目标ring将以flit和链路槽位表示容量",
    ),
    "noc_router_latency_ns": _field(
        "NoC每跳延迟",
        "当前抽象router每经过一跳增加的固定延迟。",
        "ns/hop",
        "NoC固定路径延迟。",
        "增大会线性提高NoC延迟分量。",
        "0.1到500。",
        "5 ns/hop、平均2跳产生约10 ns固定延迟。",
        "当前旧NoC模型",
    ),
    "noc_queue_depth": _field(
        "NoC队列深度",
        "当前瓶颈NoC模型可等待的请求entry数量。",
        "entry",
        "NoC入口准入。",
        "队列满时requester重试；增大可吸收突发但增加最大排队。",
        "1到4096。",
        "64表示最多64个等待请求。",
        "当前旧NoC模型；目标bufferless ring没有router等待队列",
    ),
    "noc_virtual_channels": _field(
        "NoC虚通道数",
        "为拓扑和未来容量接口保留的VC数量。",
        "VC",
        "当前配置导出。",
        "当前不改变仲裁或隔离结果，修改它不应被解释为真实VC行为。",
        "1到16。",
        "4仅作为保留参数输出。",
        "保留接口，当前不参与行为",
    ),
    "memory_controllers": _field(
        "内存控制器数",
        "独立MC MSC实例数量；每个实例维护自己的队列、token、QoS和CBusy状态。",
        "instance",
        "地址到MC的当前分配和多实例监控。",
        "增加实例通常增加总容量并分散竞争；UI聚合值必须标明求和。",
        "1到8。",
        "2表示mc0和mc1各自执行相同PARTID配置。",
    ),
    "channels_per_mc": _field(
        "每MC通道数",
        "每个MC包含的抽象内存通道数量。",
        "channel/MC",
        "MC总建模带宽计算。",
        "MC总带宽等于通道数乘单通道带宽。",
        "1到16。",
        "2通道乘128 Gbps得到256 Gbps/MC。",
        "容量近似，不含DRAM bank/row timing",
    ),
    "channel_bandwidth_gbps": _field(
        "单通道带宽",
        "每个抽象内存通道可提供的理论数据带宽。",
        "Gbps/channel",
        "MC序列化时间、利用率和BMIN可行性诊断。",
        "增大可缩短请求序列化并提高MC总容量。",
        "1到2048。",
        "128 Gbps约等于16 GB/s。",
        "容量近似，不含协议开销",
    ),
    "mc_base_latency_ns": _field(
        "MC基础服务延迟",
        "请求被MC调度后增加的固定内存服务延迟，不含排队、限速和序列化。",
        "ns",
        "MC dispatch到completion。",
        "增大会提高memory service和总延迟，但当前不会独立降低dispatch带宽。",
        "1到2000。",
        "80表示每个已调度请求至少增加80 ns服务时间。",
    ),
    "mc_queue_depth": _field(
        "MC请求缓冲深度",
        "每个MC最多容纳的等待请求数。",
        "entry/MC",
        "MC接收准入、CBusy queue ratio和调度候选。",
        "增大可保存更多突发请求，但可能形成更大排队和更慢反馈。",
        "1到8192。",
        "512表示每个MC最多512个等待请求。",
    ),
    "mc_token_bucket_window_ns": _field(
        "MC Token突发窗口",
        "当前BMIN/BMAX token bucket容量窗口，容量为max(64B, 带宽乘窗口)。",
        "ns",
        "每MC、每PARTID的BMIN和BMAX token状态。",
        "增大允许更长短时突发，减小使限制更紧但调度事件更频繁。",
        "0.1到1,000,000。",
        "100 ns和80 Gbps产生约1000B bucket容量。",
        "当前过渡算法；目标规格的BMIN/BMAX将使用上一监控周期滤波值",
    ),
    "mc_aging_ns": _field(
        "MC Aging周期",
        "当前请求每等待一个该周期获得一级effective QoS加分。",
        "ns/step",
        "MC候选评分。",
        "减小会更快提升等待请求，可能削弱基础QoS差异。",
        "0.1到1,000,000。",
        "500 ns表示等待1000 ns获得2级aging。",
        "当前逐请求年龄算法；目标低PPA实现默认关闭并改为每PARTID service-deficit",
    ),
    "mc_qos_aging_max_steps": _field(
        "MC Aging最大升档",
        "当前逐请求aging最多可增加的3-bit QoS档数。",
        "QoS level",
        "MC effective QoS计算。",
        "增大可增强防饥饿能力，但可能更快覆盖静态QoS差异。",
        "0到7；0关闭aging升档。",
        "3表示aging最多贡献+3。",
        "当前逐请求年龄算法参数",
    ),
    "mc_bmin_qos_promote": _field(
        "BMIN QoS升档",
        "当前请求拥有BMIN credit时加入effective QoS的档数。",
        "QoS level",
        "MC候选评分。",
        "增大提升UNDER_BMIN请求在竞争中的选择概率；0表示BMIN不产生调度偏好。",
        "0到7，最终effective QoS钳位到0..7。",
        "2表示BMIN credit贡献+2。",
        "当前token-credit近似参数",
    ),
    "mc_softlimit_qos_demote": _field(
        "Soft BMAX QoS降档",
        "当前softlimit请求超过BMAX token且MC存在竞争时扣减的QoS档数。",
        "QoS level",
        "MC候选评分。",
        "增大使超限流量在竞争时更弱；无竞争时保持work-conserving。",
        "0到7，最终effective QoS钳位到0..7。",
        "2表示soft超限竞争时贡献-2。",
        "当前token-credit近似参数",
    ),
    "cbusy_sample_ns": _field(
        "CBusy快速采样周期",
        "MC计算每PARTID服务带宽、队列比例和hard-block事件的快速反馈窗口。",
        "ns",
        "每MC、每PARTID CBusy状态机。",
        "减小响应更快但更易受短时波动影响；增大更平滑但反馈更慢。",
        "1到1,000,000。",
        "1000表示每1 us重新检测一次。",
    ),
    "cbusy_feedback_latency_ns": _field(
        "CBusy反馈传播延迟",
        "MC档位变化到CPU requester可见之间的模型延迟。",
        "ns",
        "CBusy事件发布路径。",
        "增大会增加队列过冲和RN持有旧档位的时间。",
        "0到100,000。",
        "50表示档位变化50 ns后影响源端OSTD。",
        "当前独立事件延迟；目标规格将随RSP/DAT返回携带sideband",
    ),
    "cbusy_release_hold_samples": _field(
        "CBusy释放保持",
        "检测压力低于当前档位后，必须连续满足的采样次数，之后只下降一级。",
        "sample",
        "CBusy恢复状态机。",
        "增大可抑制振荡但延长过度限流；提升档位不受该保持限制。",
        "1到1000。",
        "3表示连续3个低压样本后从L3降到L2。",
    ),
    "cbusy_l1_bw_ratio": _field(
        "CBusy L1带宽阈值",
        "快速窗口服务带宽除以该PARTID启用BMAX的阈值。",
        "ratio",
        "MC CBusy Level 1检测。",
        "降低会更早触发轻度源端限流。",
        "0.01到10，且L1不大于L2和L3；仅在BMAX启用且MC竞争时生效。",
        "1.0表示达到BMAX时满足L1带宽条件。",
    ),
    "cbusy_l2_bw_ratio": _field(
        "CBusy L2带宽阈值",
        "快速窗口服务带宽相对BMAX的中档阈值。",
        "ratio",
        "MC CBusy Level 2检测。",
        "降低会更早进入中度源端限流。",
        "0.01到10，必须不小于L1且不大于L3。",
        "1.1表示达到BMAX的110%时满足L2带宽条件。",
    ),
    "cbusy_l3_bw_ratio": _field(
        "CBusy L3带宽阈值",
        "快速窗口服务带宽相对BMAX的最高档阈值。",
        "ratio",
        "MC CBusy Level 3检测。",
        "降低会更早采用最严OSTD cap。",
        "0.01到10，必须不小于L2。",
        "1.25表示达到BMAX的125%时满足L3带宽条件。",
    ),
    "cbusy_l1_queue_ratio": _field(
        "CBusy L1队列阈值",
        "该PARTID当前MC排队数除以MC总queue depth的轻度阈值。",
        "ratio",
        "MC CBusy Level 1检测。",
        "降低会在较浅队列时开始源端限流。",
        "0到1，且L1不大于L2和L3。",
        "0.25表示该PARTID占用四分之一MC深度时满足L1。",
    ),
    "cbusy_l2_queue_ratio": _field(
        "CBusy L2队列阈值",
        "该PARTID队列占MC总深度的中档阈值。",
        "ratio",
        "MC CBusy Level 2检测。",
        "降低会更早进入中度OSTD限制。",
        "0到1，必须不小于L1且不大于L3。",
        "0.50表示占用一半MC深度时满足L2。",
    ),
    "cbusy_l3_queue_ratio": _field(
        "CBusy L3队列阈值",
        "该PARTID队列占MC总深度的最高档阈值。",
        "ratio",
        "MC CBusy Level 3检测。",
        "降低会更早采用最严OSTD限制。",
        "0到1，必须不小于L2。",
        "0.75表示占用四分之三MC深度时满足L3。",
    ),
    "policy": _field(
        "控制策略",
        "选择只监控、执行静态MPAM配置，或在静态控制之上运行P99慢速闭环。",
        "枚举",
        "仿真控制策略factory和每周期policy callback。",
        "no_control关闭L3/MC强制；static_mpam保持表值；closed_loop_qos可运行时修改MC QoS和背景BMAX。",
        "必须为no_control、static_mpam或closed_loop_qos。",
        "算法验证通常使用static_mpam隔离硬件机制。",
    ),
    "max_bw_step_percent": _field(
        "闭环BMAX步长",
        "closed_loop_qos每次收紧或恢复背景PARTID BMAX的相对百分比。",
        "%",
        "慢速软件闭环写MC设置表。",
        "增大响应更快但更容易过度调节；减小更平滑但收敛更慢。",
        "1到100，仅closed_loop_qos使用。",
        "10表示每次违约把背景BMAX乘0.9。",
    ),
    "p99_hysteresis": _field(
        "P99滞回比例",
        "围绕P99目标建立上下触发带，避免实际值在目标附近反复写控制。",
        "ratio",
        "closed_loop_qos违约和恢复判断。",
        "增大减少切换但允许更大目标偏差。",
        "0到1。",
        "0.1表示高于目标110%保护、低于目标90%才考虑恢复。",
    ),
    "min_hold_intervals": _field(
        "闭环最小保持周期",
        "两次慢速闭环控制更新之间至少间隔的控制周期数。",
        "control interval",
        "closed_loop_qos更新节流。",
        "增大降低振荡和写配置频率，但延长响应。",
        "1到100。",
        "3和50 us控制周期表示至少保持150 us。",
    ),
}


STIMULUS_METADATA: Dict[str, Dict[str, str]] = {
    "slot": _field(
        "激励槽位",
        "固定硬件线程行号。",
        "index",
        "8核16线程参考映射。",
        "只用于稳定映射和导出。",
        "0到15，只读。",
        "slot 7固定映射cpu3.t1。",
        "固定标识",
    ),
    "requester": _field(
        "Requester",
        "该激励固定绑定的CPU硬件线程请求源。",
        "标识",
        "CPU requester。",
        "决定OSTD、CBusy反馈和请求归因所在的源端。",
        "Web参考场景不可编辑。",
        "cpu0.t1表示core0的线程1。",
        "固定映射",
    ),
    "enabled": _field(
        "启用激励",
        "是否为该硬件线程生成workload和请求流。",
        "布尔",
        "流量生成器创建阶段。",
        "关闭后requester仍存在，但该行不注入请求。",
        "16行中至少一行必须启用。",
        "关闭cpu4.t0不会改变其他行映射。",
    ),
    "partid": _field(
        "激励PARTID",
        "请求携带的资源控制标识，L3和MC用它查找设置表。",
        "0..15",
        "每个生成请求的MPAM标签。",
        "多个线程可共享一个PARTID并共同受该分区控制。",
        "整数0到15。",
        "两个线程都选P3会共享P3的CMAX和BMAX。",
    ),
    "pmg": _field(
        "激励PMG",
        "请求携带的Performance Monitoring Group，用于同一PARTID内进一步监控归因。",
        "0..15",
        "L3和MC的(PARTID, PMG)监控key。",
        "改变PMG只改变当前监控分组，不独立改变资源控制。",
        "整数0到15；PMG作用域属于PARTID。",
        "P3/G1和P3/G2共享控制但分开统计。",
    ),
    "workload_type": _field(
        "激励类型",
        "选择地址模式、依赖和突发特征的预设。",
        "枚举",
        "流量生成器。",
        "不同类型改变局部性、可并行度和队列峰值。",
        "stream、pointer_chase、random_read、mixed_rw或bursty_dma。",
        "pointer_chase用于观察低并行依赖访问时延。",
        "当前类型仍融合若干行为；目标规格将拆分地址、操作、依赖、到达和选择策略",
    ),
    "rate_value": _field(
        "注入强度",
        "该线程生成请求的目标输入速率，具体单位由rate_unit决定。",
        "Gbps或MRPS",
        "流量生成间隔。",
        "增大提高offered traffic并可能触发L3、NoC和MC竞争。",
        "启用行必须大于0；Gbps最大4096，MRPS最大1000。",
        "6 Gbps和64B请求约对应11.7 MRPS。",
    ),
    "rate_unit": _field(
        "注入单位",
        "选择按数据位率或每秒百万请求数解释rate_value。",
        "枚举",
        "流量生成间隔换算。",
        "Gbps会随request size改变请求频率；MRPS与request size无关。",
        "gbps或mrps。",
        "4 MRPS表示平均每250 ns一个请求。",
    ),
    "request_size_bytes": _field(
        "请求字节数",
        "单个抽象memory request携带的数据字节数。",
        "byte/request",
        "流量速率换算、NoC/MC序列化和token消耗。",
        "增大单请求资源成本；同Gbps下请求数减少。",
        "16到4096。",
        "64表示每请求64B。",
    ),
    "read_ratio": _field(
        "读比例",
        "生成请求中read操作的概率。",
        "ratio",
        "流量生成器操作选择。",
        "0为全写，1为全读；当前L3/MC对写路径的功能抽象有限。",
        "0到1。",
        "0.75表示约75%读、25%写。",
        "当前功能流量标签；目标规格将补齐写终止响应和顺序",
    ),
    "working_set_mb": _field(
        "工作集大小",
        "该线程生成地址覆盖的逻辑地址范围。",
        "MiB",
        "地址生成和当前概率L3命中计算。",
        "相对允许cache容量越大，当前模型命中概率通常越低。",
        "1到262,144。",
        "1024表示1 GiB工作集。",
    ),
    "target_p99_ns": _field(
        "P99目标",
        "正值把该PARTID标记为closed_loop_qos保护对象，0表示不设置延迟目标。",
        "ns",
        "慢速闭环的保护组选择和违约判断。",
        "目标越低越容易触发提升保护组MC QoS和收紧背景BMAX。",
        "0到1,000,000；只有closed_loop_qos会自动动作。",
        "500表示希望该PARTID P99不高于500 ns。",
    ),
}


PARTID_METADATA: Dict[str, Dict[str, str]] = {
    "partid": _field(
        "PARTID",
        "固定资源控制分区编号。",
        "0..15",
        "L3和MC设置表索引。",
        "该行所有控制值都作用于同一PARTID。",
        "16行固定覆盖0到15，不可重复。",
        "P2表示设置表索引2。",
        "固定标识",
    ),
    "name": _field(
        "分区名称",
        "软件可见的分区备注名称，仅用于识别和导出。",
        "字符串",
        "配置与报告。",
        "不改变硬件控制行为。",
        "最多32个字符。",
        "latency_sensitive。",
    ),
    "monitor_enable": _field(
        "监控开关",
        "声明该PARTID的MSC监控能力启用。",
        "布尔",
        "L3和MC监控快照。",
        "关闭不应被显示为零；当前UI仍保留16行以便识别未启用状态。",
        "不改变控制表值。",
        "关闭P7监控后控制仍可保留。",
    ),
    "cpbm_enable": _field(
        "CPBM控制开关",
        "独立启用该PARTID的cache way资格位图。",
        "布尔",
        "L3 miss分配选择eligible ways之前。",
        "关闭后所有way可参与分配，CMIN/CMAX仍可独立生效。",
        "启用时CPBM至少应包含一个可达way。",
        "关闭后0x000f配置被保留但不强制。",
    ),
    "cpbm": _field(
        "CPBM位图",
        "十六进制Cache Portion Bitmap，bit N对应way N是否允许该PARTID分配。",
        "hex bitmap",
        "L3 sampled-owner miss分配资格过滤。",
        "减少bit会缩小可达容量，并钳位有效CMIN/CMAX。",
        "不能设置超过l3_ways的bit。",
        "16 ways下00ff允许way 0到7。",
    ),
    "cmin_enable": _field(
        "CMIN控制开关",
        "独立启用竞争替换时的最低占用保护。",
        "布尔",
        "L3 victim合法性判断。",
        "关闭后有效CMIN为0，CPBM和CMAX保持。",
        "所有启用CMIN合计不能超过100%。",
        "仅关闭P1 CMIN不会关闭P1 CMAX。",
    ),
    "cmin": _field(
        "CMIN比例",
        "该PARTID希望在整个物理L3中受保护的最低占用比例。",
        "%",
        "当前sampled-owner victim保护。",
        "提高会减少其他PARTID可驱逐的该PARTID sample lines；它不预分配无需求容量。",
        "0到CMAX，且不能超过CPBM可达比例。",
        "25表示有需求并竞争时保护约四分之一L3。",
        "当前直接读取sampled-owner状态；目标规格改为上一256拍滤波MPAM监控值",
    ),
    "cmax_enable": _field(
        "CMAX控制开关",
        "独立启用该PARTID的最大L3占用增长限制。",
        "布尔",
        "L3 miss分配victim选择。",
        "关闭后有效上限只受CPBM可达比例限制。",
        "配置值保留，重新启用后恢复。",
        "关闭P2 CMAX后仍受P2 CPBM限制。",
    ),
    "cmax": _field(
        "CMAX比例",
        "该PARTID在整个物理L3允许拥有的最高占用比例。",
        "%",
        "当前sampled-owner全局配额判断。",
        "达到上限后只能替换自己已拥有的eligible sampled line，不能继续增长。",
        "CMIN到100%，并钳位到CPBM可达比例；不同PARTID CMAX之和可超过100%。",
        "12.5表示最多约八分之一L3。",
        "当前直接读取sampled-owner状态；目标规格改为上一256拍滤波MPAM监控值",
    ),
    "bmin_enable": _field(
        "BMIN控制开关",
        "独立启用当前BMIN token credit和QoS升档。",
        "布尔",
        "MC候选请求评分。",
        "关闭后不产生BMIN credit和升档，其他MC控制保持。",
        "配置值保留。",
        "关闭P4 BMIN后P4基础QoS仍可生效。",
    ),
    "bmin_gbps": _field(
        "BMIN目标",
        "每个MC实例上该PARTID的最低带宽目标。",
        "Gbps/MC",
        "当前BMIN token credit和effective QoS计算。",
        "有credit时请求获得配置的BMIN QoS升档；它不是无条件带宽保证。",
        "0到BMAX；所有BMIN合计超过单MC容量时界面给出不可行警告。",
        "40表示每个MC上目标40 Gbps。",
        "当前token-credit近似；目标规格改为上一256拍滤波带宽状态",
    ),
    "bmax_enable": _field(
        "BMAX控制开关",
        "独立启用soft或hard最大带宽控制。",
        "布尔",
        "MC候选资格和QoS评分。",
        "关闭后不执行hard阻塞或soft降档，配置值和mode保留。",
        "启用时BMAX必须大于0且不小于BMIN。",
        "关闭P2 BMAX可用于对照实验。",
    ),
    "bmax_gbps": _field(
        "BMAX目标",
        "每个MC实例上该PARTID的最大带宽目标。",
        "Gbps/MC",
        "当前BMAX token bucket。",
        "soft模式只在竞争且token不足时降档；hard模式token不足时排除候选。",
        "大于0且不小于BMIN，最大4096。",
        "80表示每个MC上目标80 Gbps。",
        "当前token bucket过渡算法；目标规格改为上一256拍滤波带宽整周期门控",
    ),
    "limit_mode": _field(
        "BMAX模式",
        "选择softlimit或hardlimit的执行语义。",
        "枚举",
        "MC候选资格和effective QoS。",
        "soft保持work-conserving；hard可阻止dispatch直到token恢复。",
        "softlimit或hardlimit。",
        "soft适合观察借用，hard适合验证严格源端以下的服务限制。",
    ),
    "mc_qos_enable": _field(
        "MC QoS开关",
        "独立启用该PARTID的3-bit基础MC QoS。",
        "布尔",
        "MC本地候选评分。",
        "关闭后基础QoS为0，但aging、BMIN和soft降档仍按各自开关工作。",
        "配置值保留。",
        "关闭P1 QoS不影响NoC，因为当前NoC本来不使用此值。",
    ),
    "mc_qos": _field(
        "MC基础QoS",
        "MC本地3-bit调度优先档，7最高。",
        "0..7",
        "MC候选effective_qos计算。",
        "提高通常使有资格的请求在竞争中更早被选中，但hard BMAX仍可将其排除。",
        "整数0到7，只作用于MC。",
        "7表示最高基础档。",
    ),
    "cbusy_enable": _field(
        "CBusy控制开关",
        "启用该MC对该PARTID的四档拥塞检测和CPU源端OSTD反馈。",
        "布尔",
        "MC快速状态机与requester新请求准入。",
        "关闭后MC发布Level 0，已配置OSTD cap保留。",
        "可与BMAX独立启用；叠加时可能过度限流。",
        "CBusy-only对照可只打开此项。",
    ),
    "cbusy_l1_ostd": _field(
        "CBusy L1 OSTD上限",
        "CPU收到Level 1后该PARTID允许的新请求outstanding上限。",
        "request",
        "requester每PARTID新请求准入。",
        "值越小，轻度拥塞时源端限流越强。",
        "1到max_outstanding，且L1不小于L2和L3。",
        "24表示L1时最多24个未完成请求。",
    ),
    "cbusy_l2_ostd": _field(
        "CBusy L2 OSTD上限",
        "CPU收到Level 2后该PARTID的新请求outstanding上限。",
        "request",
        "requester每PARTID新请求准入。",
        "值越小，中度拥塞时源端限流越强。",
        "1到L1，且不小于L3。",
        "16表示L2时最多16个未完成请求。",
    ),
    "cbusy_l3_ostd": _field(
        "CBusy L3 OSTD上限",
        "CPU收到Level 3后该PARTID的新请求outstanding上限。",
        "request",
        "requester每PARTID新请求准入。",
        "值越小，严重拥塞时源端限流越强。",
        "1到L2；至少1以保留基本前向进展。",
        "4表示L3时最多4个未完成请求。",
    ),
}


OPTION_METADATA: Dict[str, Dict[str, str]] = {
    "workload_type": {
        "stream": "连续递增地址；独立请求、高带宽、低时间局部性，容易形成持续带宽压力。",
        "pointer_chase": "依赖式随机访问；后一个地址依赖前一个结果，低并行度，主要观察时延。",
        "random_read": "独立随机读；可并发发出，命中取决于工作集和允许缓存容量。",
        "mixed_rw": "随机读写混合；read_ratio决定读写比例，用于通用流量竞争。",
        "bursty_dma": "成组突发后停顿；用于观察队列峰值、过冲和背压恢复。",
    },
    "rate_unit": {
        "gbps": "数据位率；请求频率由Gbps和request_size_bytes共同换算。",
        "mrps": "每秒百万请求数；请求频率不随request_size_bytes改变。",
    },
    "limit_mode": {
        "softlimit": "token不足时请求仍eligible；只有存在竞争时降低effective QoS，无竞争可借用。",
        "hardlimit": "token不足时请求从候选集合移除，等待预算恢复后重新参与调度。",
    },
    "core_ostd_policy": {
        "shared": "两个SMT线程共享Core总容量，同时各自受Thread最大OSTD限制；空闲容量可由任一线程使用。",
        "static_partition": "按稳定线程顺序静态切分Core容量，线程不能借用另一线程未使用的份额。",
        "reserve_borrow": "每线程保留最低份额，超过保留后可竞争未保留空间；用于研究隔离与利用率折中。",
    },
    "policy": {
        "no_control": "保留监控，但关闭L3和MC资源强制及运行时策略更新。",
        "static_mpam": "执行当前16组PARTID表值，运行期间不自动修改控制。",
        "closed_loop_qos": "执行静态控制，并按周期读取保护PARTID P99，修改保护QoS和背景BMAX。",
    },
}


CONTROL_ALGORITHMS: Dict[str, Dict[str, str]] = {
    "requester-ostd": {
        "title": "CPU Requester OSTD准入",
        "summary": "在分配事务ID前，同时限制Thread、共享Core和目标MC/PARTID的未完成请求数量。",
        "inputs": "Thread与Core上限、Core策略和reserve、各层当前OSTD、请求地址解析出的home MC、该MC对PARTID延迟反馈的CBusy level和cap。",
        "state": "每Core总量/峰值/各Thread占用/pending集合/上次grant；每Thread及PARTID计数；每(PARTID,目标MC)计数和反馈表。",
        "cadence": "激励先生成地址并解析home MC；每次准入尝试组合判断；最终completion释放；CBusy事件到达时更新对应MC反馈。",
        "decision": "can_issue = Thread未满 且 Core策略允许 且 Core内(PARTID,home MC)合计OSTD低于该MC有效CBusy cap；多个eligible pending线程按确定性round-robin选择。",
        "action": "不满足时保留同一待发描述和地址，记录Thread/Core/RR/CBusy阻塞；满足后才分配transaction ID并增加全部层次计数。",
        "recovery": "L3 hit或MC返回完成时按事务记录的home MC释放全部计数；CBusy下降后只放宽后续新事务。",
        "priority": "Thread、Core和目标MC/PARTID限制取交集；CBusy不跨MC传播；static_partition和reserve_borrow先执行各自份额规则。",
        "forward_progress": "effective OSTD钳位至少为1；响应和已发请求不受准入门控。",
        "evidence": "CPU导出显示Core current/peak/limit、Thread/PARTID计数、各阻塞原因；目标MC导出显示每(PARTID,MC)的current/peak/cap/CBusy/stall。",
        "boundary": "这是可配置的事务表抽象，不声称对应某款商业CPU的entry数量或SMT分配算法；REQ Ring接受能力将在后续bufferless ring模型中接入同一准入链。",
    },
    "l3-cpbm": {
        "title": "L3 CPBM Way资格控制",
        "summary": "在L3 sampled-owner miss分配前，用位图限制该PARTID可选择的way。",
        "inputs": "PARTID、cpbm_enable、十六进制CPBM和配置ways。",
        "state": "每PARTID设置表；每个抽样set的way owner、PMG、tag和last_touch。",
        "cadence": "每次访问抽样set且发生模型miss时执行。",
        "decision": "eligible_way = CPBM中对应bit为1；关闭CPBM时全部way eligible。",
        "action": "victim选择只扫描eligible way；无合法victim时记录allocation denial。",
        "recovery": "修改或关闭CPBM后，后续分配立即使用新资格；已有line不被主动搬迁或清除。",
        "priority": "先应用CPBM过滤，再执行CMAX增长和CMIN victim保护。",
        "forward_progress": "无合法victim时该次抽样分配旁路，不阻塞请求完成。",
        "evidence": "L3视图显示configured/effective CPBM、reachable percent、allocation denials和sampled owners。",
        "boundary": "当前只对每8个set中的抽样set维护显式owner；目标规格将对所有set/tag/way执行真实分配。",
    },
    "l3-cmin": {
        "title": "L3 CMIN替换保护",
        "summary": "保护已有需求填充的最低sampled-owner占用，不预留空cache。",
        "inputs": "请求PARTID、victim owner、CMIN%、CPBM可达比例和当前全局sampled-owner计数。",
        "state": "每PARTID设置；所有抽样set的way owner；当前周期保护跳过计数。",
        "cadence": "每次抽样set模型miss需要选择其他owner victim时执行。",
        "decision": "effective CMIN=min(configured CMIN, CPBM reachable%)；quota=ceil(sampled_capacity*CMIN%)；只有owner_count>quota的line可被驱逐。",
        "action": "跳过处于或低于CMIN quota的victim；若没有其他合法victim，则拒绝该次抽样分配。",
        "recovery": "owner占用高于quota后自然重新可被驱逐；关闭CMIN立即把有效quota置0。",
        "priority": "CPBM先过滤way；请求者CMAX决定能否增长；随后CMIN保护victim owner。",
        "forward_progress": "CMIN只阻止抽样owner转移，不阻塞访问或响应；无victim时采用allocation bypass。",
        "evidence": "显示configured/effective CMIN、quota lines、sampled occupancy、protected eviction计数和allocation denial。",
        "boundary": "当前控制直接读取完整sampled-owner状态，尚未使用上一256个L3本地拍的滤波MPAM监控值；当前L3命中仍是概率模型。",
    },
    "l3-cmax": {
        "title": "L3 CMAX占用增长限制",
        "summary": "限制PARTID继续增加全局sampled-owner数量。",
        "inputs": "请求PARTID、CMAX%、CPBM可达比例和当前全局sampled-owner计数。",
        "state": "每PARTID设置；所有抽样set的way owner和LRU last_touch。",
        "cadence": "每次抽样set模型miss分配时执行。",
        "decision": "effective CMAX=min(configured CMAX, CPBM reachable%)；quota=floor(sampled_capacity*CMAX%)；count达到quota后禁止获取其他owner或空way。",
        "action": "达到CMAX后只允许替换请求者自己的eligible LRU line；没有自己的line则拒绝抽样分配。",
        "recovery": "请求者sampled owner下降到quota以下或配置提高后可再次增长；关闭CMAX后由CPBM可达比例形成上限。",
        "priority": "CPBM限定候选way；CMAX先判断请求者能否增长；未达到CMAX时仍必须遵守victim CMIN。",
        "forward_progress": "拒绝抽样分配不阻塞请求完成，只影响近似cache owner和后续命中概率。",
        "evidence": "显示configured/effective CMAX、quota lines、sampled owner count、占用比例和allocation denial。",
        "boundary": "当前控制直接读取sampled-owner状态；目标规格要求使用上一256拍滤波监控值并维护所有真实set/tag/way。",
    },
    "mc-bmin": {
        "title": "MC BMIN Token-Credit升档",
        "summary": "当前实现用按速率补充的credit判断请求是否获得BMIN QoS提升。",
        "inputs": "PARTID BMIN Gbps、请求size、token window、BMIN enable和当前时间。",
        "state": "每MC、每PARTID的min token数量及last_update时间。",
        "cadence": "MC比较候选和服务请求时按经过时间惰性补充token。",
        "decision": "bucket容量=max(64B, BMIN速率*window)；token足够支付请求size时标记UNDER_BMIN并增加配置QoS档。",
        "action": "effective_qos加入bmin_qos_promote；请求服务后消耗对应BMIN token。",
        "recovery": "token随时间补充并在容量处饱和；关闭BMIN后不再产生升档。",
        "priority": "hard BMAX资格先过滤；BMIN升档与base QoS、aging和soft降档共同计算并钳位0..7。",
        "forward_progress": "BMIN只改变选择偏好，不阻止其他有资格请求；不能保证不可行配置仍达到目标。",
        "evidence": "MC视图显示BMIN、preferred/promoted request、base/effective QoS和实测带宽。",
        "boundary": "这是当前token-credit近似。目标规格要求每256个MC本地拍根据上一周期滤波MPAM带宽形成UNDER_BMIN状态和滞回。",
    },
    "mc-bmax": {
        "title": "MC BMAX Soft/Hard限制",
        "summary": "当前实现以每MC、每PARTID token bucket决定soft降档或hard候选阻塞。",
        "inputs": "BMAX Gbps、mode、request size、token window、MC竞争状态和soft demotion。",
        "state": "每PARTID max token及last_update；周期soft request、hard block和throttle计数。",
        "cadence": "候选比较时检查token；服务请求时消耗；全阻塞时计算最短token恢复时间并重新调度。",
        "decision": "soft：token不足且queue_length>1时扣减QoS，无竞争仍eligible；hard：token不足时从候选集合排除。",
        "action": "soft不直接停流，只降低effective QoS；hard延迟dispatch并累计throttle delay和block事件。",
        "recovery": "token按BMAX速率补充并在bucket容量饱和；足够支付request size后恢复资格或取消soft超限。",
        "priority": "hard资格过滤先于QoS；soft降档参与base+aging+BMIN-soft公式；CBusy可同时限制源端OSTD。",
        "forward_progress": "BMAX必须大于0；hard等待按缺失token计算，token恢复后请求重入候选；响应不受限制。",
        "evidence": "显示BMAX/mode、soft penalty、hard blocks、throttle delay、effective QoS、带宽和队列。",
        "boundary": "当前为token bucket。目标规格已决定hard BMAX改为上一256拍滤波带宽驱动的整周期资格门控，因此会天然产生过冲和锯齿。",
    },
    "mc-qos": {
        "title": "MC 3-bit Effective QoS仲裁",
        "summary": "在当前每PARTID队首候选之间组合基础QoS、逐请求aging、BMIN升档和soft BMAX降档。",
        "inputs": "base mc_qos、请求等待时间、aging参数、BMIN credit、soft超限和hard资格。",
        "state": "每PARTID FIFO队列；请求enqueue time和sequence；token状态。",
        "cadence": "每次MC可dispatch新请求时重新计算候选。",
        "decision": "effective_qos=clamp(base+aging_steps+BMIN_promote-soft_demote,0,7)；选择最高值，同值选择最老sequence。",
        "action": "从对应PARTID队首弹出请求，记录评分组成并开始MC服务。",
        "recovery": "等待会增加aging直到上限；token和竞争变化会取消BMIN/soft修正。",
        "priority": "hard BMAX先移除不合格候选；MC QoS不传播到当前NoC。",
        "forward_progress": "aging可降低长期饥饿风险；若全部候选hard-block则等待最早token恢复。",
        "evidence": "显示base/effective QoS平均、最小、最大，aging/promote/demote次数和被选请求。",
        "boundary": "当前只比较每PARTID队首且使用逐请求时间戳。目标规格要求共享buffer全深度candidate、同档旋转slot扫描，默认关闭逐请求aging。",
    },
    "mc-cbusy": {
        "title": "MC四档CBusy到CPU OSTD闭环",
        "summary": "用快速带宽、队列和hard-block压力生成Level 0..3，并延迟反馈到CPU源端。",
        "inputs": "快速窗口服务字节、该PARTID队列深度、BMAX、hard-block事件、六个阈值和三档OSTD cap。",
        "state": "每MC、每PARTID 2-bit level、release sample计数、窗口字节、hard block和监控统计。",
        "cadence": "每cbusy_sample_ns检测；档位事件再经过feedback_latency到requester。",
        "decision": "取满足queue ratio或竞争下bandwidth/BMAX阈值的最高档；出现hard block时至少Level 2。",
        "action": "升档立即发布；CPU只限制匹配PARTID的新请求OSTD，不取消请求、不阻塞响应、不改MC QoS。",
        "recovery": "压力降低后连续release_hold_samples才下降一级；逐级恢复，直到Level 0。",
        "priority": "多个MC在当前requester按最高level聚合，同level取最小cap；与configured OSTD取更严格值。",
        "forward_progress": "OSTD cap至少1；已发请求和返回通道不受CBusy门控。",
        "evidence": "显示带宽比、队列比、level、duty、transition、反馈延迟、effective OSTD和source stall。",
        "boundary": "当前反馈是独立定时事件且按requester全局PARTID聚合；目标规格将sideband随RSP/DAT返回并按目标MC分别限流。",
    },
    "policy-mode": {
        "title": "控制模式与P99慢速闭环",
        "summary": "决定是否执行静态L3/MC控制，以及是否根据保护PARTID P99周期性修改MC设置。",
        "inputs": "policy、保护PARTID P99目标和实测值、滞回、最小保持周期、步长、背景PARTID集合。",
        "state": "最后更新周期；每MC、每背景PARTID的初始BMAX；当前设置表。",
        "cadence": "每control_interval_ns调用一次；两次动作至少间隔min_hold_intervals。",
        "decision": "P99>target*(1+h)时违约；所有保护对象低于target*(1-h)时可恢复。",
        "action": "违约时保护PARTID MC QoS加1并钳位7，背景BMAX乘(1-step%)；恢复时背景BMAX逐步回到初始值。",
        "recovery": "只有进入低滞回带且保持周期满足时逐步恢复；不会自动降低已提升的保护QoS。",
        "priority": "no_control关闭硬件强制；static_mpam只执行表值；closed_loop_qos叠加运行时写表。CBusy快环独立工作。",
        "forward_progress": "背景BMAX下限钳位0.001 Gbps；目标不可达、过度限流或振荡作为分析结果继续仿真。",
        "evidence": "控制记录显示时间、MSC、PARTID、字段、旧值、新值和P99触发原因；效果页同时显示目标与实际。",
        "boundary": "当前是演示性软件策略，不代表Linux MPAM/resctrl或具体芯片firmware算法；目标规格后续需单独定义稳定性和目标函数。",
    },
}


CONTROL_FIELD_ALGORITHMS: Dict[str, Dict[str, str]] = {
    "parameters": {
        "max_outstanding": "requester-ostd",
        "core_max_outstanding": "requester-ostd",
        "core_ostd_policy": "requester-ostd",
        "thread_ostd_reserve": "requester-ostd",
        "mc_token_bucket_window_ns": "mc-bmax",
        "mc_aging_ns": "mc-qos",
        "mc_qos_aging_max_steps": "mc-qos",
        "mc_bmin_qos_promote": "mc-bmin",
        "mc_softlimit_qos_demote": "mc-bmax",
        "cbusy_sample_ns": "mc-cbusy",
        "cbusy_feedback_latency_ns": "mc-cbusy",
        "cbusy_release_hold_samples": "mc-cbusy",
        "cbusy_l1_bw_ratio": "mc-cbusy",
        "cbusy_l2_bw_ratio": "mc-cbusy",
        "cbusy_l3_bw_ratio": "mc-cbusy",
        "cbusy_l1_queue_ratio": "mc-cbusy",
        "cbusy_l2_queue_ratio": "mc-cbusy",
        "cbusy_l3_queue_ratio": "mc-cbusy",
        "policy": "policy-mode",
        "max_bw_step_percent": "policy-mode",
        "p99_hysteresis": "policy-mode",
        "min_hold_intervals": "policy-mode",
    },
    "partid": {
        "cpbm_enable": "l3-cpbm",
        "cpbm": "l3-cpbm",
        "cmin_enable": "l3-cmin",
        "cmin": "l3-cmin",
        "cmax_enable": "l3-cmax",
        "cmax": "l3-cmax",
        "bmin_enable": "mc-bmin",
        "bmin_gbps": "mc-bmin",
        "bmax_enable": "mc-bmax",
        "bmax_gbps": "mc-bmax",
        "limit_mode": "mc-bmax",
        "mc_qos_enable": "mc-qos",
        "mc_qos": "mc-qos",
        "cbusy_enable": "mc-cbusy",
        "cbusy_l1_ostd": "mc-cbusy",
        "cbusy_l2_ostd": "mc-cbusy",
        "cbusy_l3_ostd": "mc-cbusy",
    },
    "stimulus": {
        "target_p99_ns": "policy-mode",
    },
}


def config_metadata_payload() -> Dict[str, object]:
    return {
        "version": "2026-06-21",
        "fields": {
            "parameters": PARAMETER_METADATA,
            "stimulus": STIMULUS_METADATA,
            "partid": PARTID_METADATA,
        },
        "options": OPTION_METADATA,
        "control_algorithms": CONTROL_ALGORITHMS,
        "control_field_algorithms": CONTROL_FIELD_ALGORITHMS,
    }


def _missing_sections(
    entries: Mapping[str, Mapping[str, str]],
    required: Iterable[str],
    prefix: str,
) -> List[str]:
    issues: List[str] = []
    for name, entry in entries.items():
        for section in required:
            if not str(entry.get(section, "")).strip():
                issues.append(f"{prefix}.{name}: missing {section}")
    return issues


def audit_config_metadata(
    defaults: Mapping[str, object],
) -> List[str]:
    issues = _missing_sections(
        PARAMETER_METADATA,
        REQUIRED_FIELD_SECTIONS,
        "parameters",
    )
    issues.extend(
        _missing_sections(
            STIMULUS_METADATA,
            REQUIRED_FIELD_SECTIONS,
            "stimulus",
        )
    )
    issues.extend(
        _missing_sections(
            PARTID_METADATA,
            REQUIRED_FIELD_SECTIONS,
            "partid",
        )
    )
    issues.extend(
        _missing_sections(
            CONTROL_ALGORITHMS,
            REQUIRED_CONTROL_SECTIONS,
            "control",
        )
    )

    scalar_defaults = {
        key
        for key, value in defaults.items()
        if not isinstance(value, (list, dict))
    }
    for name in sorted(scalar_defaults - set(PARAMETER_METADATA)):
        issues.append(f"parameters.{name}: missing metadata")

    partid_rows = defaults.get("partid_configs", [])
    if isinstance(partid_rows, list) and partid_rows:
        for name in sorted(set(partid_rows[0]) - set(PARTID_METADATA)):
            issues.append(f"partid.{name}: missing metadata")

    stimulus_rows = defaults.get("stimulus_configs", [])
    if isinstance(stimulus_rows, list) and stimulus_rows:
        for name in sorted(set(stimulus_rows[0]) - set(STIMULUS_METADATA)):
            issues.append(f"stimulus.{name}: missing metadata")

    for group, fields in CONTROL_FIELD_ALGORITHMS.items():
        for field_name, algorithm_name in fields.items():
            if algorithm_name not in CONTROL_ALGORITHMS:
                issues.append(
                    f"{group}.{field_name}: unknown control {algorithm_name}"
                )

    expected_options = {
        "workload_type": {
            "stream",
            "pointer_chase",
            "random_read",
            "mixed_rw",
            "bursty_dma",
        },
        "rate_unit": {"gbps", "mrps"},
        "limit_mode": {"softlimit", "hardlimit"},
        "policy": {
            "no_control",
            "static_mpam",
            "closed_loop_qos",
        },
    }
    for field_name, values in expected_options.items():
        missing = values - set(OPTION_METADATA.get(field_name, {}))
        for value in sorted(missing):
            issues.append(f"options.{field_name}.{value}: missing metadata")
    return issues
